### PR TITLE
AbfV1 fixes

### PR DESCRIPTION
**Pull request by t-b**
I'm currently fixing some issues with the ABFv1 support.

This is still very much WIP, I'll polish it in the next days.

(I'm just opening it now to prevent duplicated work)

### CODE REVIEW

**Comment by swharden** [comment]
It's looking good! I won't merge until you say the PR is ready.

What are you referencing as you add these new header values? [stimfit/abfheadr.h](https://github.com/neurodroid/stimfit/blob/master/src/libbiosiglite/biosig4c%2B%2B/t210/abfheadr.h)?

**Comment by swharden** [comment]
In case you hadn't seen it, Abfhelp.chm provided with the ABF1 SDK is very useful. I'm amazed I got this far without realizing this document exists [Abfhelp.zip](https://github.com/swharden/pyABF/files/3838838/Abfhelp.zip). I overlooked it because I only ever looked at the newer SDK.

image

**Comment by swharden** [comment]
I converted the ABF1 SDK documentation to markdown. It looks like it contains byte offsets for every variable you could want! I hope you find it useful. 

https://github.com/swharden/pyABF/blob/master/docs/advanced/abf-file-format/abf1-file-format.md

**Comment by t-b** [comment]
@swharden Thanks for the link. I did not know that this exists I've used the C header file from biosig. But I'll have a look at the markdown docu.

**Comment by t-b** [comment]
@swharden Updated.

Although this should be in the final state now, please wait with merging until I did some more testing.
Do the CI tests include some regression testing? I changed some of the channel handling code for V1.

**Comment by swharden** [comment]
> Although this should be in the final state now, please wait with merging until I did some more testing.

Sounds good! Let me know when you're ready for me to merge.

> Do the CI tests include some regression testing? I changed some of the channel handling code for V1.

Yes, tests are run on all new commits (including those in this PR). Hover over the green checkbox next to the commit hash for details. Tests are in [/tests](https://github.com/swharden/pyABF/tree/master/tests), and feel free to add some ABF1-specific tests if you like.

**Comment by swharden** [comment]
@t-b I started creating tests in [/tests/test_abfinfo.py](https://github.com/swharden/pyABF/blob/master/tests/test_abfinfo.py) which compare ABFINFO.exe header values to those determined by pyABF. My goal is to add tests to confirm accuracy validate all top-level ABF variables. As I got started I noticed ABF1 creation datetime didn't include milliseconds, so I fixed it. However now I see that you've already fixed this issue with this PR. To prevent you from having to resolve merge conflicts I'll stop all work until this PR is merged. Let me know when it's at a good place and I can merge it in.

If you're inspired to add tests to [/tests/test_abfinfo.py](https://github.com/swharden/pyABF/blob/master/tests/test_abfinfo.py) to verify your header values are accurate, feel free to. If not, I'll write them after you say this PR is ready to merge.

Thanks again for all your help!

**Comment by t-b** [comment]
@swharden Should be ready.

I actually think you should drop python 2 support. It is EOL in 10 days.

**Comment by swharden** [comment]
> @swharden Should be ready.

Thanks @t-b it's looking good! I'll work on merging this in this weekend.

> I actually think you should drop python 2 support. It is EOL in 10 days.

I agree, and while we're dropping support for old versions of Python I'd also like to drop support for Python 3.5 so we can use f-strings. We can throw a message if the user tries to install pyabf on an older system #98

**Pull request merged**
