### PR TITLE
Feature/enhance protocol section

### PR DESCRIPTION
**Pull request by t-b**

### CODE REVIEW

**Comment by swharden** [comment]
Headers have been regenerated to reflect these updates:
https://github.com/swharden/pyABF/tree/master/data

**Comment by swharden** [comment]
Note that this patch uses the warnings module without importing it, causing a hard crash when ABFs are loaded which don't map to a known telegraphed instrument or digitizer. This problem was fixed in [pyABF 2.0.20](https://github.com/swharden/pyABF/releases/tag/2.0.20)

**Comment by swharden** [comment]
18711001.abf and 18713001.abf are examples of ABFs which do not map properly

https://github.com/swharden/pyABF/tree/master/data

**Comment by t-b** [comment]
@swharden Good catch. Do you know the name of the hardware which was used? I can then also extend [_mapDigitizerType](https://github.com/swharden/pyABF/blob/679ba22eb249b17e8ef5023ce633631c5d9ba6b7/src/pyabf/structures.py#L243).

**Comment by swharden** [comment]
I contacted the person who emailed me those ABFs and asked this question. If she sends me that information over email I’ll post it here. I also gave her a link to this page, so she may post this information herself. I’m interested to learn what equipment she’s using!

**Comment by swharden** [comment]
_”We are using Molecular Devices/ Axon Instruments hardware with pClamp 10 software. We have the Multiclamp 700B commander and the Axon Digidata 1550B digitizer.”_

**Pull request merged**
