### PR TITLE
Feature/better epoch handling

### PR DESCRIPTION
**Pull request by t-b**

### CODE REVIEW

**Comment by swharden** [comment]
FYI, I think this broke somewhere but I don't have time at the moment to see where. I can tell it's broken because "runTests.py" crashes with:

```
  File "c:/Users/swharden/Documents/GitHub/pyABF/tests/runTests.py", line 36, in <module>
    runFunctionInFile(PATH_PROJECT+"/data/generate-data-index.py")
  File "c:/Users/swharden/Documents/GitHub/pyABF/tests/runTests.py", line 30, in runFunctionInFile
    getattr(theModule, functionName)()
  File "c:\Users\swharden\Documents\GitHub\pyABF/data/generate-data-index.py", line 202, in go
    plotThumbnail(abf)
  File "c:\Users\swharden\Documents\GitHub\pyABF/data/generate-data-index.py", line 166, in plotThumbnail
    ax2.plot(abf.sweepX, abf.sweepC, color='r')
  File "C:\Users\swharden\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\__init__.py", line 1710, in inner
    return func(ax, *args, **kwargs)
  File "C:\Users\swharden\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\axes\_axes.py", line 1437, in plot
    for line in self._get_lines(*args, **kwargs):
  File "C:\Users\swharden\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 404, in _grab_next_args
    for seg in self._plot_args(this, kwargs):
  File "C:\Users\swharden\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 384, in _plot_args
    x, y = self._xy_from_xy(x, y)
  File "C:\Users\swharden\AppData\Local\Continuum\Anaconda3\lib\site-packages\matplotlib\axes\_base.py", line 243, in _xy_from_xy
    "have shapes {} and {}".format(x.shape, y.shape))
ValueError: x and y must have same first dimension, but have shapes (100000,) and (0,)
```

**Comment by t-b** [comment]
@swharden THanks I'll look into it.

**Comment by t-b** [comment]
@swharden Maybe it is 7408d46 where I return an empty array if the DAC is turned off?

**Comment by swharden** [comment]
Actually, I did have time to find the problem! It was a quick fix. https://github.com/swharden/pyABF/commit/589309f5cfd48c95929849bd516475a1c90a12f2 I had always assumed `len(sweepX) == len(sweepC)` and throughout the code used things like:

```python
matplotlib.pyplot.plot(sweepX, sweepC)
```

... so setting sweepC to empty crashes the scripts which attempt to plot the command. It's all good now. Of note, I updated all the headers and the improved version numbers and other properties now show up:

https://github.com/swharden/pyABF/tree/master/data

**Pull request merged**
