### PR TITLE
ABF loading optimization and improved support for variable-length sweeps

### PR DESCRIPTION
**Pull request by lucarossi147**
I'm working with pyABF and I noticed that the workflow was using some old versions.
Working with the code I also noticed that to transpose a matrix were done two distinct operations instead of one that is already implemented in the np library

### CODE REVIEW

**Comment by swharden** [comment]
Hi @lucarossi147, thank you for this improvement! I'll merge this and publish a new package on pypi soon (probably this evening).

Note that I've been on the fence about using a hard-coded version matrix in the CI system. I used to use this strategy, but since this library is so stable it changes less often than the list of supported python versions, and hard-coded versions often broke the build. There's no perfect solution I guess. Version `3.x` tests against the latest Python version. Is there a version string that tests against the oldest supported python version? That would be ideal to prevent the build from breaking as GitHub Actions changes their list of supported versions

**Comment by swharden** [comment]
lol, we can try this, but I don't think `2.x` is supported

I think `3.6` is the minimum supported version, but that's no longer supported by GitHub Actions

I'm not sure if there's a code like `3._` to compliment `3.x` to represent the oldest-supported python 3 version, if that makes selse

**Comment by swharden** [comment]
... actually, I wonder if we can use `setup-python` to test against python version 3.6, and `3.x`

https://github.com/actions/setup-python

I can take a closer look tonight if you don't feel like figuring that out now. Thanks again for your contribution! I'll put this down for now, but pick it up later today 👍

**Comment by lucarossi147** [comment]
I'm discovering just now that this space kinda works like a chat lol

**Comment by swharden** [comment]
> I'm discovering just now that this space kinda works like a chat lol

Yep! It's hit or miss though... If a library is no longer actively maintained messages can rot for years and it's super frustrating 🤷

**Comment by lucarossi147** [comment]
I tried to use 2.x just for fun but it breaks stuff so I removed the commit, I'm sure we can test only against the 3.6 version and the 3.x, I'll change it now.
Also, a co-worker and I are working on another change inside the abf.py file, it looks like with sweeps of different lengths there could be incorrect results, especially with multi-channel devices.
We are verifying some tests and rewriting the "critical part" so if everything goes as expected you'll probably receive another pull request any day soon 💪

**Comment by swharden** [comment]
> Also, a co-worker and I are working on another change inside the abf.py file, it looks like with sweeps of different lengths there could be incorrect results, especially with multi-channel devices.
> We are verifying some tests and rewriting the "critical part" so if everything goes as expected you'll probably receive another pull request any day soon 💪

Sounds great! If you have a small ABF file that demonstrates the error I would be happy to help add it to the sample data and the test system.

I recognize it's a little confusing figuring out how to add new test ABFs

If real-time collaboration would be helpful, I'm usually around on the ScottPlot.net discord most evenings (EST)

Thanks again for your contributions! 🚀

**Comment by lucarossi147** [comment]
That would be awsome! I'll be working on it tomorrow, more or less all day, however I'll send you what I found either here or on discord.
I tried to add the 3.6 version in the ci github action but seems like there are some problems (at least with macos) we could either remove the 3.6 version and stick with the 3.x or use a later version, bigger then 3.6

**Comment by lucarossi147** [comment]
Hi, I tried to fix the workflow but it seems like macos systems can't pull down a 3.6 version of python so the ez fix was to just test it against the 3. 8

However the real deal for me is the bug fix for multi channel and multi sweep abf files. I had to change even the known values in the tests because they were wrong.
An example of a file that broke it can be found at the following link [https://github.com/Elements-SRL/EDA_python/blob/main/src/res/EpisodicData/episodic%20several%20sweeps.abf](url) 
or attached here [episodic several sweeps.zip](https://github.com/swharden/pyABF/files/9617251/episodic.several.sweeps.zip).

With the fix it now works exactly as expected.

Keep me posted with the updates on this topic so that I can download the newest version of this package and continue to work on my internship project!

**Comment by swharden** [comment]
Hey @lucarossi147, sorry for my delay. I was sick for the last couple weeks and didn't use the computer much, but I'm back again. Well, mostly. I live in north Florida and a hurricane may disrupt power later this week...

> Hi, I tried to fix the workflow but it seems like macos systems can't pull down a 3.6 version of python so the ez fix was to just test it against the 3. 8

No worries! I'll make a few tweaks to the CI file and merge this tonight.

> However the real deal for me is the bug fix for multi channel and multi sweep abf files. I had to change even the known values in the tests because they were wrong.

Fantastic! Thanks for the fix!  🚀 

For the record, this is what one of those files looks like in ClampFit

image

I may replace setup.py with a more modern packaging system, but either way I'll update pypi within the next few days 👍 

> Keep me posted with the updates on this topic so that I can download the newest version of this package and continue to work on my internship project!

**Comment by swharden** [comment]
> Keep me posted with the updates on this topic so that I can download the newest version of this package and continue to work on my internship project!

I decided to leave the packaging system like it is and deploy using GitHub Actions. pyabf 2.3.7 is now live! Let me know if it does the trick

https://pypi.org/project/pyabf/

```
pip install --upgrade pyabf
```

> continue to work on my internship project!

If you're participating in hacktoberfest this year, I plan to register as a maintainer and mark pull requests appropriately so contributors can get credit. If you're interested in the free t-shirt and stickers and stuff, I'd be happy to review any improvements you have for this library (including the docs!). https://hacktoberfest.com/

I'm also thinking of revamping the API so `abf.GetSweep()` returns a `Sweep` dataclass 🤯 ... It's probably how pyabf should have been designed from the start. The change wouldn't be breaking (it would be _in addition_ to what's there now), but I hope it could simplify interacting with ABFs (and their episodic protocols). If you're interested in brainstorming how that would look and/or implementing it, I'd be happy to discuss this with you further!

Thanks again for your work on this PR 🚀✨

**Comment by lucarossi147** [comment]
Don't worry, hope everything is fine now and that there won't be hurricanes 🤞.

However thanks again for your help 🎉

**Pull request merged**
